field: b0d567f5-9a6d-4988-ad46-4b76323444db # Post Content
fieldLayouts:
  4b13cfb3-3c0f-4b63-ade0-bfe7adcf8ac5:
    tabs:
      -
        elements:
          -
            fieldUid: 51c97ce3-fefb-497b-b29d-9ffdbc379cae # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  51c97ce3-fefb-497b-b29d-9ffdbc379cae: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:28fe9c2f-cfc3-46cb-b61c-0a8848f9187d' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:28fe9c2f-cfc3-46cb-b61c-0a8848f9187d' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:28fe9c2f-cfc3-46cb-b61c-0a8848f9187d' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
