columnSuffix: null
contentColumnType: string
fieldGroup: a57f871f-284a-42cf-b1bf-5c202be4d0c5 # Blog
handle: featuredImage
instructions: ''
name: 'Featured Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:28fe9c2f-cfc3-46cb-b61c-0a8848f9187d' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:28fe9c2f-cfc3-46cb-b61c-0a8848f9187d' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
