columnSuffix: nrqtuosw
contentColumnType: text
fieldGroup: ea1f0d66-614d-4b37-b72a-16ffb6a80562 # ContactUs
handle: intro
instructions: ''
name: Intro
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: 'Add an intro content paragraph here.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
