columnSuffix: null
contentColumnType: string
fieldGroup: a57f871f-284a-42cf-b1bf-5c202be4d0c5 # Blog
handle: topics
instructions: ''
name: 'Post Categories'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:0bbe1a78-28d2-4089-84b9-1a61a75874cd' # Topics
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
