defaultPlacement: end
enableVersioning: true
handle: thankyou
name: ThankYou
propagationMethod: all
siteSettings:
  c4dd095f-d021-49d1-acf9-66e3093fd9e3: # Craft Cms 3
    enabledByDefault: true
    hasUrls: true
    template: _singles/thanks
    uriFormat: contact/thanks
type: single
